- hosts: localhost
  roles:
    - williamyeh.oracle-java
    - geerlingguy.java
      #   - wildfly
    - nvm
    - { role: tecris.maven, maven_major: 3, maven_release: 3.5.3, maven_home_parent_directory: /opt }
    - geerlingguy.docker
    - nginx
    - gitflow
    - geerlingguy.jenkins
    - ansible-phantomjs
  vars:
    java_version: 8
    java_subversion: 161
    java_download_from_oracle: false
    jdk_tarball_file: jdk-8u161-linux-x64
    java_packages: openjdk-8-jdk
